services:
  app:
    build: ./app
    container_name: web-app
    hostname: web-app
    volumes: ["./app/src:/appcode"]
    ports:
      - 8501:8501
    environment:
      API_BASE: http://web-api:4000
      DOCKER_CONTAINER: "true"

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes: ["./api:/apicode"]
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_NAME: BallWatch
      MYSQL_ROOT_PASSWORD: ballwatch

  db:
    image: mysql:8.0
    container_name: mysql_db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: ballwatch
      MYSQL_DATABASE: BallWatch
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
      - mysql_data:/var/lib/mysql
    ports:
      - 3200:3306

volumes:
  mysql_data: {}
